### ISSUE TITLE
Soap 1.2

### ISSUE THREAD

**Issue by querdenker2k** [shumonsharif/quarkus-cxf#2]
I tried to deploy a Soap 1.2 Service, but it's always produced as 1.1.
Tried it with this annotation: @BindingType(javax.xml.ws.soap.SOAPBinding.SOAP12HTTP_BINDING)
Is it already somehow possible?

**Comment by shumonsharif** [comment]
Soap 1.2 bindings are not yet supported; will certainly look into implementing this.

**Comment by dufoli** [comment]
in cxfprocessor build , you must handle BindingType annotation by registering in QuarkusCxfProcessor.java with  DotName.createSimple and used it to send it to the servlet
and in CXFQuarkusServlet 
factory.setBindingId(SOAPBinding.SOAP12HTTP_BINDING);

**Comment by shumonsharif** [comment]
@dufoli Great to see you on here, and thanks for the tip.  I haven't been able to look into this recently, but will start this weekend.  I may reach out to you with questions if needed; thanks so much once again!

**Comment by dufoli** [comment]
I have just push an MR. Can you test it ?

**Comment by dufoli** [comment]
I have not run a single test on it. Just code quickly before work ;-)

**Comment by dufoli** [comment]
I start a merge request and that point and introduce a test for the second issue. But test failed currently.

**Comment by shumonsharif** [comment]
Hey @dufoli I'm looking at the merge request and test for the second issue now.  Will keep you posted.

**Comment by shumonsharif** [comment]
@dufoli Thank you so much for the soap 1.2 merge request; it seems to be working fine, and I just merged it.  As far as the failed unit test; I think I found a completely new, unrelated bug.  I will open a ticket for it shortly.
